---
name: CI
'on':
    pull_request:
    push:
        branches:
            - master

jobs:
    UnitTests:
        name: Run PHPUnit tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out the codebase
              uses: actions/checkout@v3

            - name: Run PHPUnit tests
              run: make unit-tests

    Psalm:
        name: Run Psalm
        runs-on: ubuntu-latest

        steps:
            - name: Check out the codebase
              uses: actions/checkout@v3

            - name: Run Psalm
              run: make psalm
