---
name: Release
'on':
    push:
        tags:
            - '*'

jobs:
    Composer:
        name: Install composer dependencies with caching
        runs-on: ubuntu-latest

        steps:
            - name: Check out the codebase
              uses: actions/checkout@v3

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Run composer install
              uses: php-actions/composer@v6

    Psalm:
        name: Run Psalm
        runs-on: ubuntu-latest

        steps:
            - name: Check out the codebase
              uses: actions/checkout@v3

            - name: Run Psalm
              run: make psalm

    UnitTests:
        name: Run PHPUnit tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out the codebase
              uses: actions/checkout@v3

            - name: Run PHPUnit tests
              run: make unit-tests
